language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
notifications:
  email:
    on_success: change
    on_failure: always
env:
 - MPI=mpich2
 - MPI=mpich3
before_install:
 - sudo apt-get update -q
 - sh ./conf/travis-install-mpi.sh $MPI
script: ARCH=x86_64 CC=mpicc cmake . && make
