language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
notifications:
  email:
    on_success: change
    on_failure: always
env:
 - MPI=mpich2
 - MPI=mpich3
before_install:
 - sudo apt-get update -q
 - sudo apt-get install -y -qq lcov curl
 - sh ./conf/travis-install-mpi.sh $MPI
script:
 - mkdir build && cd build
 - ARCH=x86_64 CC=mpicc cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug -DROSS_BUILD_MODELS=ON ..
 - make
 - make test
 - make coveralls
